---

- name: postgres_server
  hosts: postgres_server
  become: yes
  vars_files:
     - vars/main.yml
  roles:
    - general
    - apache
    - PostgreSQL

      #Prøve installere postgres på samme måte. Kanskje også git?
