---

- name: Install postgres_server
  hosts: postgres_server
  become: yes
  vars_files:
     - vars/main.yml
  roles:
    - general
    - apache
    - PostgreSQL

- name: Install ambari_server
  hosts: ambari_server
  become: yes
  roles:
    - general
    - apache
    - GoogleChrome
    - ambari
