---

- name: Create Ambari Repo 2.6.0.0
  get_url:
    url: http://public-repo-1.hortonworks.com/ambari/ubuntu14/2.x/updates/2.6.2.0/ambari.list
    dest: /etc/apt/sources.list.d/ambari.list

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: B9733A7A07513CAD

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: install ambari-server
  apt: name=ambari-server state=latest
